# -*- coding: utf-8 -*-
"""Laws of Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRZE5v0Y15XiC9whCk4-LhYmqA1fcY3C
"""

# Program to demonstrate Laws of Sets
# User selects the law to verify

A = {1, 2, 3}
B = {3, 4, 5}
C = {3, 5, 6}

# Universal Set
U = {1, 2, 3, 4, 5, 6, 7}

# Empty Set
E = set()

# Complements
A_comp = U - A
B_comp = U - B


def commutative_law():
    print("\n--- Commutative Law ---")

    # Union
    left = A | B
    right = B | A

    print("A ∪ B =", left)
    print("B ∪ A =", right)
    print("A ∪ B = B ∪ A :", left == right)

    # Intersection
    left = A & B
    right = B & A

    print("\nA ∩ B =", left)
    print("B ∩ A =", right)
    print("A ∩ B = B ∩ A :", left == right)


def associative_law():
    print("\n--- Associative Law ---")

    # Union
    left = (A | B) | C
    right = A | (B | C)

    print("(A ∪ B) ∪ C =", left)
    print("A ∪ (B ∪ C) =", right)
    print("Union Associative Law :", left == right)

    # Intersection
    left = (A & B) & C
    right = A & (B & C)

    print("\n(A ∩ B) ∩ C =", left)
    print("A ∩ (B ∩ C) =", right)
    print("Intersection Associative Law :", left == right)


def distributive_law():
    print("\n--- Distributive Law ---")

    # A ∪ (B ∩ C)
    left = A | (B & C)
    right = (A | B) & (A | C)

    print("A ∪ (B ∩ C) =", left)
    print("(A ∪ B) ∩ (A ∪ C) =", right)
    print("Union Distributive Law :", left == right)

    # A ∩ (B ∪ C)
    left = A & (B | C)
    right = (A & B) | (A & C)

    print("\nA ∩ (B ∪ C) =", left)
    print("(A ∩ B) ∪ (A ∩ C) =", right)
    print("Intersection Distributive Law :", left == right)


def identity_law():
    print("\n--- Identity Law ---")

    # A ∪ ∅ = A
    left = A | E
    right = A

    print("A ∪ ∅ =", left)
    print("A =", right)
    print("A ∪ ∅ = A :", left == right)

    # A ∩ U = A
    left = A & U
    right = A

    print("\nA ∩ U =", left)
    print("A =", right)
    print("A ∩ U = A :", left == right)


def complement_law():
    print("\n--- Complement Law ---")

    print("A =", A)
    print("A' =", A_comp)

    # A ∪ A' = U
    left = A | A_comp
    right = U

    print("\nA ∪ A' =", left)
    print("U =", right)
    print("A ∪ A' = U :", left == right)

    # A ∩ A' = ∅
    left = A & A_comp
    right = E

    print("\nA ∩ A' =", left)
    print("∅ =", right)
    print("A ∩ A' = ∅ :", left == right)


def demorgan_law():
    print("\n--- De Morgan's Laws ---")

    # First De Morgan's Law
    # (A ∪ B)' = A' ∩ B'

    left = U - (A | B)
    right = A_comp & B_comp

    print("(A ∪ B)' =", left)
    print("A' ∩ B' =", right)
    print("(A ∪ B)' = A' ∩ B' :", left == right)

    # Second De Morgan's Law
    # (A ∩ B)' = A' ∪ B'

    left = U - (A & B)
    right = A_comp | B_comp

    print("\n(A ∩ B)' =", left)
    print("A' ∪ B' =", right)
    print("(A ∩ B)' = A' ∪ B' :", left == right)


# ==============================
# MAIN PROGRAM
# ==============================

print("====================================")
print("        LAWS OF SETS")
print("====================================")

print("\nSet A =", A)
print("Set B =", B)
print("Set C =", C)
print("Universal Set U =", U)

while True:

    print("\n====================================")
    print("Select a Law")
    print("====================================")

    print("1. Commutative Law")
    print("2. Associative Law")
    print("3. Distributive Law")
    print("4. Identity Law")
    print("5. Complement Law")
    print("6. De Morgan's Laws")
    print("7. All Laws")
    print("8. Exit")

    choice = int(input("\nEnter your choice: "))

    if choice == 1:
        commutative_law()

    elif choice == 2:
        associative_law()

    elif choice == 3:
        distributive_law()

    elif choice == 4:
        identity_law()

    elif choice == 5:
        complement_law()

    elif choice == 6:
        demorgan_law()

    elif choice == 7:
        commutative_law()
        associative_law()
        distributive_law()
        identity_law()
        complement_law()
        demorgan_law()

    elif choice == 8:
        print("\nProgram ended.")
        break

    else:
        print("\nInvalid choice! Please enter 1 to 8.")