# -*- coding: utf-8 -*-
"""Laws of Sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iRZE5v0Y15XiC9whCk4-LhYmqA1fcY3C
"""

# Program to demonstrate Laws of Sets
# User selects number of sets and the law to verify


# ==============================
# TAKE NUMBER OF SETS
# ==============================

while True:
    n = int(input("How many sets do you want to enter (1-3)? "))

    if 1 <= n <= 3:
        break
    else:
        print("Please enter a number between 1 and 3.")


# ==============================
# TAKE SETS FROM USER
# ==============================

sets = {}

for i in range(n):
    elements = input(
        f"Enter elements of Set {chr(65 + i)} separated by spaces: "
    )

    sets[chr(65 + i)] = set(map(int, elements.split()))


# Assign sets
A = sets["A"]

if n >= 2:
    B = sets["B"]

if n >= 3:
    C = sets["C"]


# ==============================
# UNIVERSAL SET
# ==============================

U_input = input(
    "\nEnter elements of Universal Set U separated by spaces: "
)

U = set(map(int, U_input.split()))

E = set()


# ==============================
# COMMUTATIVE LAW
# ==============================

def commutative_law():

    if n < 2:
        print("\nCommutative Law requires at least 2 sets.")
        return

    print("\n--- Commutative Law ---")

    # Union
    left = A | B
    right = B | A

    print("A ∪ B =", left)
    print("B ∪ A =", right)
    print("A ∪ B = B ∪ A :", left == right)

    # Intersection
    left = A & B
    right = B & A

    print("\nA ∩ B =", left)
    print("B ∩ A =", right)
    print("A ∩ B = B ∩ A :", left == right)


# ==============================
# ASSOCIATIVE LAW
# ==============================

def associative_law():

    if n < 3:
        print("\nAssociative Law requires 3 sets.")
        return

    print("\n--- Associative Law ---")

    # Union
    left = (A | B) | C
    right = A | (B | C)

    print("(A ∪ B) ∪ C =", left)
    print("A ∪ (B ∪ C) =", right)
    print("Union Associative Law :", left == right)

    # Intersection
    left = (A & B) & C
    right = A & (B & C)

    print("\n(A ∩ B) ∩ C =", left)
    print("A ∩ (B ∩ C) =", right)
    print("Intersection Associative Law :", left == right)


# ==============================
# DISTRIBUTIVE LAW
# ==============================

def distributive_law():

    if n < 3:
        print("\nDistributive Law requires 3 sets.")
        return

    print("\n--- Distributive Law ---")

    # A ∪ (B ∩ C)
    left = A | (B & C)
    right = (A | B) & (A | C)

    print("A ∪ (B ∩ C) =", left)
    print("(A ∪ B) ∩ (A ∪ C) =", right)
    print("Union Distributive Law :", left == right)

    # A ∩ (B ∪ C)
    left = A & (B | C)
    right = (A & B) | (A & C)

    print("\nA ∩ (B ∪ C) =", left)
    print("(A ∩ B) ∪ (A ∩ C) =", right)
    print("Intersection Distributive Law :", left == right)


# ==============================
# IDENTITY LAW
# ==============================

def identity_law():

    print("\n--- Identity Law ---")

    # A ∪ ∅ = A
    left = A | E
    right = A

    print("A ∪ ∅ =", left)
    print("A =", right)
    print("A ∪ ∅ = A :", left == right)

    # A ∩ U = A
    left = A & U
    right = A

    print("\nA ∩ U =", left)
    print("A =", right)
    print("A ∩ U = A :", left == right)


# ==============================
# COMPLEMENT LAW
# ==============================

def complement_law():

    print("\n--- Complement Law ---")

    A_comp = U - A

    print("A =", A)
    print("A' =", A_comp)

    # A ∪ A' = U
    left = A | A_comp
    right = U

    print("\nA ∪ A' =", left)
    print("U =", right)
    print("A ∪ A' = U :", left == right)

    # A ∩ A' = ∅
    left = A & A_comp
    right = E

    print("\nA ∩ A' =", left)
    print("∅ =", right)
    print("A ∩ A' = ∅ :", left == right)


# ==============================
# DE MORGAN'S LAWS
# ==============================

def demorgan_law():

    if n < 2:
        print("\nDe Morgan's Laws require at least 2 sets.")
        return

    print("\n--- De Morgan's Laws ---")

    A_comp = U - A
    B_comp = U - B

    # First De Morgan's Law
    # (A ∪ B)' = A' ∩ B'

    left = U - (A | B)
    right = A_comp & B_comp

    print("(A ∪ B)' =", left)
    print("A' ∩ B' =", right)
    print("(A ∪ B)' = A' ∩ B' :", left == right)

    # Second De Morgan's Law
    # (A ∩ B)' = A' ∪ B'

    left = U - (A & B)
    right = A_comp | B_comp

    print("\n(A ∩ B)' =", left)
    print("A' ∪ B' =", right)
    print("(A ∩ B)' = A' ∪ B' :", left == right)


# ==============================
# MAIN PROGRAM
# ==============================

print("\n====================================")
print("          LAWS OF SETS")
print("====================================")

print("\nEntered Sets:")

for name, value in sets.items():
    print(f"Set {name} =", value)

print("Universal Set U =", U)


while True:

    print("\n====================================")
    print("Select a Law")
    print("====================================")

    print("1. Commutative Law")
    print("2. Associative Law")
    print("3. Distributive Law")
    print("4. Identity Law")
    print("5. Complement Law")
    print("6. De Morgan's Laws")
    print("7. All Laws")
    print("8. Exit")

    choice = int(input("\nEnter your choice: "))

    if choice == 1:
        commutative_law()

    elif choice == 2:
        associative_law()

    elif choice == 3:
        distributive_law()

    elif choice == 4:
        identity_law()

    elif choice == 5:
        complement_law()

    elif choice == 6:
        demorgan_law()

    elif choice == 7:
        commutative_law()
        associative_law()
        distributive_law()
        identity_law()
        complement_law()
        demorgan_law()

    elif choice == 8:
        print("\nProgram ended.")
        break

    else:
        print("\nInvalid choice! Please enter 1 to 8.")